#!/bin/bash
# dbwebb: tool to manage course repos
#
# The MIT License (MIT)
#
# Copyright (c) 2014-2015 Mikael Roos (me@mikaelroos.se)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
DBW_VERSION="1.1.1"
mapfile usage <<EOD
Utility dbwebb version $DBW_VERSION by Mikael Roos (mos@dbwebb.se), to work with dbwebb course repositories.

Usage: dbwebb [options] <command> [arguments]

Command:

  check             Check and print out details on the environment.
  config            Create, or re-create the config file.
  selfupdate        Update dbwebb-cli installation.
  sshkey            Create and install ssh-keys to avoid using password.
  login             Login to the remote server using ssh and sshkeys if available.
  init-server       Init the server by creating a directory structure on it.

Command (to manage course repos):

  ls                List all locally installed course repos within \$DBW_HOME.
  repo              List all supporoted remote course repos.
  clone repo-name   Clone and locally install a remote course repo.

Command (for a valid course repo):

  init-me           Init the directory me/ by copying files and directories from default/.
  update            Update the courserepo with latest updates from the master repo.
  upload [part]     Upload current directory to the the server.
  download [part]   Download current directory from the server (overwrite all files, be careful).
  create labid      Create a laboration, use additional argument for naming what lab to create.
  validate [part]   Validate (and upload) your files using the remote server.
  publish [part]    Upload, Validate and Publish your course results to the web.
  inspect kmom [user]   Inspect a kmom for yourself or a specific user, needs teacher privilegies
                        to check another students kmom.

Options:

  -i, --inspect  Prints help with commands for inspect.
  -v, --verbose  Verbose, print out what's happening.
  -y, --yes      Do not wait for my input, just proceed.
  -h, --help     Print this message and exit.
  --version      Print version and exit.
  
EOD



mapfile version <<EOD
dbwebb version $DBW_VERSION

EOD



mapfile badUsage <<EOD
For an overview of the command, execute:
dbwebb --help

EOD



mapfile inspectUsage <<EOD
Commands useful at the server with respect to dbwebb inspect, needs extra privilegies.

Open up for inspect by setting group and chmod for directories and files.
sudo /usr/local/sbin/setpre-dbwebb-kurser.bash acronym

Add or delete as member of the dbwebb-group (execute on all servers)
sudo update-dbwebb-kurser.bash -a acronym
sudo update-dbwebb-kurser.bash -d acronym

Execute command as the user dbwebb.
sudo -u dbwebb script

EOD
# --------------- DBWEBB FUNCTIONS PHASE START ---------------

#
# Create the config file .dbwebb.config.
#
function createConfig()
{
    local first=$1
    local noInput=$2
    local acronym

    if [ -z $first ]
    then

        printf "The config-file '$DBW_CONFIG_FILE_NAME' will now be created in your home directory: '$HOME'"

    elif [ $first = "update" ]
    then

        printf "Your config file will be automatically updated. Then re-run your command.\n"

    elif [ $first = "upgrade" ]
    then

        printf "Your config file will be automatically updated."

    elif [ $first = "create" ]
    then

        printf "I will now re-create the configuration file '$DBW_CONFIG_FILE_NAME' in your home directory: '$HOME'."

    fi


    if [[ ! $noInput ]]; then
        DBW_USER=${DBW_USER:-$USER}
        printf "\nWhat is your student acronym? [$DBW_USER] "
        read acronym
    fi

    acronym=${acronym:-$DBW_USER}

    echo "DBW_USER='$acronym'"                > "$DBW_CONFIG_FILE"
    echo "DBW_VERSION_CONFIG='$DBW_VERSION'" >> "$DBW_CONFIG_FILE"

    printf "\n$MSG_OK The config file '$DBW_CONFIG_FILE' is now up-to-date."
    printf "\n\n"
}



#
# Update the config-file if needed
#
function updateConfigIfNeeded()
{
    local what=$1

    if [ -z "$DBW_VERSION_CONFIG" -o ! "$DBW_VERSION" = "$DBW_VERSION_CONFIG" ]
    then
        createConfig "$what" "no-user-input"
        exit 2
    fi
}



#
# Check for installed commands
#
function checkCommand()
{
    local COMMAND="$1"

    if ! hash "$COMMAND" 2>/dev/null; then
        printf "Command $COMMAND not found."
    else 
        printf "$( which $COMMAND )"
    fi
}



#
# Clone a remote repos
#
reposClone()
{
    local repo="$1"
    local repos=(python javascript1 linux webapp htmlphp)

    if [ ! -d "$DBW_HOME" ]; then
        printf "\nYou have not set \$DBW_HOME nor do you have a directory \$HOME/$DBW_BASEDIR."
    else
        ok=0
        for i in ${repos[@]}; do
            if [ "$repo" == "${i}" ]; then
                
                ok=1
                if [ -d "$DBW_HOME/$repo" ]; then
                    printf "\n$MSG_FAILED to clone. There seem to exist a directory with this name already."
                    printf "\n"
                else
                    cmd="$GIT clone https://github.com/mosbth/$repo"
                    printf "\nCloning remote course repo and making a local installation."
                    printf "\nMoving to '$DBW_HOME'"
                    printf "\n$cmd"
                    cd "$DBW_HOME"
                    $cmd
                fi
            fi
        done

        if [ $ok -eq 0 ]; then
            printf "\n$MSG_FAILED to clone remote repo, unknown repo '$repo'. Use '$DBW_EXECUTABLE repos' to get a list of supported repos."
            printf "\n"
            dbwebb2PrintShortUsage
        fi
    fi
}



#
# Selfupdate
#
selfUpdate()
{
    INTRO="Selfupdating dbwebb-cli from https://github.com/mosbth/dbwebb-cli.\nInstallation directory is: '$DBW_INSTALL_DIR'."
    COMMAND="cd '$DBW_INSTALL_DIR'; $GIT pull"
    MESSAGE="to update dbwebb-cli installation directory."
    executeCommand "$INTRO" "$COMMAND" "$MESSAGE"
}



#
# Execute a command in a controlled manner
#
executeCommand()
{
    INTRO="$1"

    if [ $SKIP_READLINE = "no" ]
    then
        printf "\n$INTRO"
        printf "\nPress a key to continue..."
        read void
    fi

    REALLY="$4"
    if [ ! -z $REALLY ]
    then
        printf "\nAre you really sure? [yN] "
        read answer
        default="n"
        answer=${answer:-$default}

        if [ ! \( "$answer" = "y" -o "$answer" = "Y" \) ]
        then
            printf "Exiting...\n"
            exit 0
        fi
    fi

    COMMAND=$2

    if [ $VERY_VERBOSE = "yes" ]
    then
        printf "\nExecuting command:"
        printf "\n$COMMAND"
        printf "\n-----------------------------------------"
        printf "\n"
    fi

    bash -c "$COMMAND"
    STATUS=$?

    if [ $VERY_VERBOSE = "yes" ]
    then
        printf "\n-----------------------------------------"
    fi

    MESSAGE=$3
    if [ $STATUS = 0 ]
    then
        printf "\n$MSG_OK $MESSAGE"
    else
        printf "\n$MSG_FAILED $MESSAGE"
    fi
    printf "\n"
    printf "\n"

    return $STATUS
}



#
# Check if within a valid course repo or exit
#
function checkIfValidCourseRepoOrExit()
{
    if [ "$DBW_COURSE_REPO_VALID" != "yes" ]; then
        printf "$MSG_FAILED Could not find file '$DBW_COURSE_FILE_NAME', this is not a valid course repo."
        printf "\nThis command must be executed within a valid course repo."
        printf "\n"
        exit 1
    fi
}



#
# Set proper rights for files and directories
#
setChmod()
{
    if [ $VERY_VERBOSE = "yes" ]; then
        printf "\nEnsuring that all files and directories are readable for all, below $DBW_COURSE_DIR."
    fi

    $FIND "$DBW_COURSE_DIR" -type d -exec chmod u+rwx,go+rx {} \;  
    $FIND "$DBW_COURSE_DIR" -type f -exec chmod u+rw,go+r {} \;   
}



#
# Convert course specific module to path on disk
#
mapCmdToDir()
{
    local CMD="$1"
    local RES=""

    if [ -z "$CMD" ]; then 
        return
    fi 

    case "$CMD" in
        example)    RES="example" ;;
        tutorial)   RES="tutorial" ;;
        me)         RES="me" ;;
        kmom01)     RES="me/kmom01" ;;
        kmom02)     RES="me/kmom02" ;;
        kmom03)     RES="me/kmom03" ;;
        kmom04)     RES="me/kmom04" ;;
        kmom05)     RES="me/kmom05" ;;
        kmom06)     RES="me/kmom06" ;;
        kmom10)     RES="me/kmom10" ;;
    esac

    if [ ! -z $RES ]; then 
        printf "$RES"
        return
    fi 

    case "$DBW_COURSE" in
        htmlphp)
            case "$CMD" in
                lab1)       RES="me/kmom02/lab1" ;;
                lab2)       RES="me/kmom03/lab2" ;;
                lab3)       RES="me/kmom04/lab3" ;;
                lab4)       RES="me/kmom05/lab4" ;;
                lab5)       RES="me/kmom06/lab5" ;;
            esac
            ;;

        python)
            case "$CMD" in
                hello)      RES="me/kmom01/hello" ;;
                plane)      RES="me/kmom01/plane" ;;

                lab1)       RES="me/kmom02/lab1" ;;
                lab2)       RES="me/kmom03/lab2" ;;
                lab3)       RES="me/kmom04/lab3" ;;
                lab4)       RES="me/kmom05/lab4" ;;
                lab5)       RES="me/kmom06/lab5" ;;
                lab6)       RES="me/kmom06/lab6" ;;

                marvin1)    RES="me/kmom02/marvin1" ;;
                marvin2)    RES="me/kmom03/marvin2" ;;
                marvin3)    RES="me/kmom04/marvin3" ;;
                marvin4)    RES="me/kmom05/marvin4" ;;
                marvin5)    RES="me/kmom06/marvin5" ;;

                game1)      RES="me/kmom04/game1" ;;
                game2)      RES="me/kmom05/game2" ;;
                game3)      RES="me/kmom06/game3" ;;

                adventure)  RES="me/kmom10/adventure" ;;
            esac
            ;;

        javascript1)
            case "$CMD" in
                sandbox)      RES="me/kmom01/sandbox" ;;
                hangman)      RES="me/kmom06/hangman" ;;
                intelligence) RES="me/kmom10/intelligence" ;;

                lab1)       RES="me/kmom02/lab1" ;;
                lab2)       RES="me/kmom03/lab2" ;;
                lab3)       RES="me/kmom04/lab3" ;;
                lab4)       RES="me/kmom04/lab4" ;;
                lab5)       RES="me/kmom05/lab5" ;;

                flag1)      RES="me/kmom02/flag1" ;;
                flag2)      RES="me/kmom03/flag2" ;;
                flag3)      RES="me/kmom04/flag3" ;;
                flag4)      RES="me/kmom05/flag4" ;;
                flag5)      RES="me/kmom06/flag5" ;;

                baddie1)    RES="me/kmom02/baddie1" ;;
                baddie2)    RES="me/kmom03/baddie2" ;;
                baddie3)    RES="me/kmom04/baddie3" ;;
                #baddie4)    RES="me/kmom05/baddie4" ;;
                #baddie5)    RES="me/kmom06/baddie5" ;;
            esac
            ;;

        linux)
            case "$CMD" in
                lab1)       RES="me/kmom02/lab1" ;;
                lab2)       RES="me/kmom03/lab2" ;;
                lab3)       RES="me/kmom04/lab3" ;;
                lab4)       RES="me/kmom05/lab4" ;;
                lab5)       RES="me/kmom06/lab5" ;;
            esac
            ;;

        webapp)
            case "$CMD" in
                lab1)       RES="me/kmom02/lab1" ;;
                lab2)       RES="me/kmom03/lab2" ;;
                lab3)       RES="me/kmom04/lab3" ;;
                lab4)       RES="me/kmom05/lab4" ;;
                lab5)       RES="me/kmom06/lab5" ;;
            esac
            ;;
    esac

    printf "$RES"
    return
}



#
# Get path to dir to check, use both parts of courses and fallback
# to absolute and relative paths.
#
function getPathToDirectoryFor()
{
    local dir="$( mapCmdToDir $1 )" 
    
    if [ -z "$command" ]; then
        echo "$DBW_CURRENT_DIR"
    elif [ -z "$dir" -a -d "$command" ]; then
        echo "$command"
    elif [ -z "$dir" -a -d "$DBW_CURRENT_DIR/$command" ]; then
        echo "$DBW_CURRENT_DIR/$command"
    elif [ -d "$DBW_COURSE_DIR" -a -d "$DBW_COURSE_DIR/$dir" ]; then
        echo "$DBW_COURSE_DIR/$dir"
    else 
        printf "\n$MSG_FAILED The item '$command' was mapped to directory '$dir' which is not a valid directory."
        printf "\n"
        exit 1
    fi
}



#
# Validate the uploaded files
#
createUploadDownloadPaths()
{
    SUBDIR="$( mapCmdToDir $ITEM )"

    if [ -z "$WHAT" -o -z "$WHERE" ]; then
        printf "$MSG_FAILED Missing argument for source or destination. Perhaps re-create the config-file?"
        printf "\n\n"
        exit 1
    fi

    if [ ! -z "$ITEM" -a -z "$SUBDIR" ]; then
        printf "\n$MSG_FAILED Not a valid combination  course: '$DBW_COURSE' and item: '$ITEM'."
        printf "\n\n"
        exit 1
    fi

    if [ ! -z "$SUBDIR" ]; then
        WHAT="$WHAT/$SUBDIR/"
        WHERE="$WHERE/$SUBDIR/"
    else
        WHAT="$WHAT/"
        WHERE="$WHERE/"
    fi

    if [ ! -d "$WHAT" ]; then
        printf "\n$MSG_FAILED Target directory is not a valid directory: '$WHAT'"
        printf "\n\n"
        exit 1
    fi
}



#
# Validate the uploaded files
#
validateUploadedResults()
{
    WHAT="$1"
    WHERE="$2"
    ITEM="$3"
    SUBDIR=""

    createUploadDownloadPaths

    local LOG="$HOME/.dbwebb-validate.log"
    local INTRO="I will now upload files to the remote server and validate them."
    local COMMAND1="$RSYNC_CMD '$WHAT' '$WHERE'"
    local COMMAND2="$SSH_CMD 'cd $DBW_BASEDIR/$DBW_COURSE; dbwebb-validate -n $IGNORE_FAULTS $WHAT' | tee '$LOG';"
    local MESSAGE="to validate course results. Saved a log of the output, review it as:\nless -R '$LOG'"
    executeCommand "$INTRO" "$COMMAND1; $COMMAND2" "$MESSAGE"
}



#
# Validate and Publish the uploaded files
#
publishResults()
{
    WHAT="$1"
    WHERE="$2"
    ITEM="$3"
    SUBDIR=""

    createUploadDownloadPaths

    local LOG="$HOME/.dbwebb-publish.log"
    local INTRO="I will now try to init the remote server and create a directory where all uploaded files will reside."
    local COMMAND1="$RSYNC_CMD '$WHAT' '$WHERE'"
    local COMMAND2="$SSH_CMD 'cd $DBW_BASEDIR/$DBW_COURSE; dbwebb-validate $IGNORE_FAULTS $WHAT' | tee '$LOG';"
    local MESSAGE="to validate and publish all course results. Saved a log of the output, review it as:\nless -R $LOG"
    executeCommand "$INTRO" "$COMMAND1; $COMMAND2" "$MESSAGE"

    if [ $? -eq 0 ]
    then
        printf "Your files are now"
    else
        printf "Some of your files might be"
    fi
    printf " published on $DBW_BASEURL"
    printf "\n"
}



#
# Inspect uploaded files
#
inspectResults()
{
    WHAT=$1
    WHO=$2
    INTRO="I will now inspect the choosen kmom for the choosen user, if you have privilegies to do that."
    LOG="$HOME/.dbwebb-inspect.log"
    COMMAND="$SSH_CMD 'cd $DBW_BASEDIR/$DBW_COURSE; bin/dbwebb-inspect $WHAT $WHO' | tee '$LOG'; "
    MESSAGE="to inspect the course results. Saved a log of the output, review it as:\nless -R '$LOG'"

    #COMMAND="$SSH_CMD 'cd $DBW_BASEDIR/$DBW_COURSE; bin/dbwebb-inspect $WHAT $WHO'"
    #MESSAGE="to inspect the course results."

    #if [ "$USER" = "$WHO" ]
    #then
        #upload="$UPLOAD"
    #else
        #upload="$UPLOAD_MINIMAL"
    #fi

    #executeCommand "$INTRO" "$upload; $COMMAND" "$MESSAGE"
    executeCommand "$INTRO" "$COMMAND" "$MESSAGE"
}



# --------------------- To be validated -------------------------------


#
# Create a lab
#
createLab()
{
    LAB="$1"
    INTRO="Create laboration $LAB."
    COMMAND="bin/dbwebb-create \"$LAB\""
    MESSAGE="to create the lab."
    executeCommand "$INTRO" "$COMMAND" "$MESSAGE"
}




# -----------------------PERHAPS USE THES LATER ON BUT NOT FOR NOW -----------------------

#
# Upload results to the server
#
uploadToServer()
{
    subdir=${DBW_CURRENT_DIR#"$DBW_COURSE_DIR/"}

    INTRO="Your current working directory '$DBW_CURRENT_DIR' will now be uploaded to remote server."
    COMMAND="$RSYNC_CMD '$DBW_CURRENT_DIR/' '$DBW_REMOTE_DESTINATION/$subdir/'"
    MESSAGE="to upload files."
    executeCommand "$INTRO" "$COMMAND" "$MESSAGE"
}



#
# Download from the server
#
downloadFromServer()
{
    subdir=${DBW_CURRENT_DIR#"$DBW_COURSE_DIR/"}

    INTRO="WARNING: Downloading remote '$DBW_REMOTE_DESTINATION/$subdir/\n         to the current working directory '$DBW_CURRENT_DIR/'.\nWARNING: Local files MAY BE overwritten."
    COMMAND="$RSYNC_CMD '$DBW_REMOTE_DESTINATION/$subdir/' '$DBW_CURRENT_DIR/'"
    MESSAGE="to download files."
    executeCommand "$INTRO" "$COMMAND" "$MESSAGE" "REALLY?"
}


#------------------------- HERE ARE THE MAIN COMMANDS -------------------------------


#
# Create default files.
#
function dbwebb-init-me()
{
    local meDefault="$DBW_COURSE_DIR/.default/"
    local me="$DBW_COURSE_DIR/me/"

    local intro="Initiating the directory 'me/' by copying directory structure and files from the directory '.default/' (will not overwrite existing files)."
    local command="$RSYNC -av --exclude README.md --ignore-existing \"$meDefault\" \"$me\""
    local message="to init the directory 'me/'."

    checkIfValidCourseRepoOrExit
    executeCommand "$intro" "$command" "$message"
}



#
# Init directory structure at the server.
#
function dbwebb-init-server()
{    
    local intro="Intiating the remote server '$DBW_HOST' by connecting as '$DBW_USER' and creating directories (if needed) where all uploaded files will reside."
    # TODO Should use DBW_BASEDIR 
    local command="$SSH_CMD 'sh -c \"if [ ! -d dbwebb-kurser ]; then mkdir dbwebb-kurser; fi; chmod 700 dbwebb-kurser; echo; echo \"dbwebb-kurser:\"; ls -l dbwebb-kurser; if [ ! -d www/dbwebb-kurser ]; then mkdir www/dbwebb-kurser; fi; chmod 755 www/dbwebb-kurser; echo; echo \"www/dbwebb-kurser:\"; ls -l www/dbwebb-kurser\"'"
    local message="to init the server."

    checkIfValidCourseRepoOrExit
    executeCommand "$intro" "$command" "$message"
}



#
# Create and use ssh-keys to login.
#
function dbwebb-sshkey()
{
    local sshkey="$HOME/.ssh/dbwebb"

    if [ ! -d "$HOME/.ssh" ]
    then
        mkdir "$HOME/.ssh"
    fi

    local intro="First we need to create a ssh key and store it locally."
    local command="ssh-keygen -t dsa -f '$sshkey' -N ''"
    local message="to create the ssh key."
    executeCommand "$intro" "$command" "$message"

    # Bug (?) om Cygwin & win 8
    # TODO refactor 
    if [ $IS_CYGWIN = "yes" ]
    then
        chgrp -vR "$CYGWIN_DEFAULT_GROUP" "$HOME/.ssh"
    fi

    chmod 700 "$HOME/.ssh"
    chmod 600 "$sshkey" "$sshkey.pub"

    intro="I will now install the ssh-key at the remote server."
    command="cat '$sshkey.pub' | ssh $DBW_USER@$DBW_HOST 'sh -c \"if [ ! -d .ssh ]; then mkdir .ssh; fi; chmod 700 .ssh; touch .ssh/authorized_keys; cat >> .ssh/authorized_keys\"'"
    message="to install the ssh-keys."    
    executeCommand "$intro" "$command" "$message"
}



#
# Login to the server
#
function dbwebb-login()
{
    local intro="I will now login to the server '$DBW_HOST' as '$DBW_USER' using ssh-keys if available."
    local command="$SSH_CMD"
    local message="to establish the connection."
    
    executeCommand "$intro" "$command" "$message"
}



#
# Update course repo to latest version
#
function dbwebb-update()
{
    local intro="Update course-repo with latest changes from its master at GitHub."
    local command="$GIT pull"
    local message="to update course repo."
    
    checkIfValidCourseRepoOrExit
    executeCommand "$intro" "$command" "$message"
}



#
# Display information on the environment
#
function dbwebb-check()
{
    printf "\nDetails on installed utilities."
    printf "\n------------------------------------"
    printf "\n"
    printf "\nbash:                  %s" "$( checkCommand $BASH )"
    printf "\ngit:                   %s" "$( checkCommand $GIT )"
    printf "\nssh:                   %s" "$( checkCommand $SSH )"
    printf "\nrsync:                 %s" "$( checkCommand $RSYNC )"
    printf "\nwget:                  %s" "$( checkCommand $WGET )"
    printf "\ncurl:                  %s" "$( checkCommand $CURL )"
    printf "\n"
    printf "\n"

    printf "\nDetails on the dbwebb-environment."
    printf "\n------------------------------------"
    printf "\n"
    printf "\nOperatingsystem:       $DBW_OS"
    printf "\nCommand issued:        $DBW_EXECUTABLE"
    printf "\nVersion of dbwebb is:  $DBW_VERSION"
    printf "\nPath to executable:    '$DBW_EXECUTABLE_DIR'"
    printf "\nConfig-file:           '$DBW_CONFIG_FILE'"
    printf "\nWorking directory:     '$DBW_CURRENT_DIR'"
    printf "\nLocal user:            '$USER'"
    printf "\nLocal homedir:         '$HOME'"
    printf "\nRemote user:           '$DBW_USER'"
    printf "\nRemote host:           '$DBW_HOST'"
    printf "\n"
    printf "\n"

    printf "\nDetails on home for course-repos."
    printf "\n------------------------------------"
    printf "\n"

    if [ -d "$DBW_HOME" ]; then
        printf "\nHome of course repos:  '$DBW_HOME'"
        printf "\n"
        printf "\nContent of directory is:"
        printf "\n"
        ls -lF "$DBW_HOME"
    else 
        printf "\nThere is no specific home defined for the course repos."
        printf "\nYou have not set \$DBWEBB_HOME nor do you have a directory \$HOME/$DBW_BASEDIR."
    fi

    printf "\n"
    printf "\n"

    printf "\nDetails on current course-repo."
    printf "\n------------------------------------"
    printf "\n"

    if [ "$DBW_COURSE_REPO_VALID" = "yes" ]; then
        printf "\nCurrent course-repo:   '$DBW_COURSE'"
        printf "\nCourse directory:      '$DBW_COURSE_DIR'"
        printf "\nCourse-repo version:   $( $GIT describe --always )"
        printf "\n\nLatest update to course repo was:"
        printf "\n"
        $GIT log -1
    else 
        printf "\nThis is not a valid course repo."
    fi
    printf "\n"
    printf "\n"
}



#
# ls $DBWEBB_HOME
#
function dbwebb-ls()
{
    if [ -d "$DBW_HOME" ]; then
        cd "$DBW_HOME"
        printf $( pwd )
        printf "\n"
        ls -lF
    else 
        printf "\nYou have not set \$DBWEBB_HOME nor do you have a directory \$HOME/$DBW_BASEDIR."
    fi
    printf "\n"
}



#
# List all available remote repos
#
function dbwebb-repo()
{
    printf "\nThe following remote course repos are supported."
    printf "\n"
    printf "\n python       https://github.com/mosbth/python"
    printf "\n javascript1  https://github.com/mosbth/javascript1"
    printf "\n linux        https://github.com/mosbth/linux"
    printf "\n webapp       https://github.com/mosbth/webapp"
    printf "\n htmlphp      https://github.com/mosbth/htmlphp"
    printf "\n"
    printf "\n"
}



#
# Create or re-create the config file.
#
function dbwebb-config()
{
    createConfig
}



#
# Push/upload results to the server
#
function dbwebb-upload()
{
    #pushToServer "" "$" "$2"
    
    WHAT="$DBW_COURSE_DIR"
    WHERE="$DBW_REMOTE_DESTINATION"
    ITEM="$1"
    SUBDIR=""

    checkIfValidCourseRepoOrExit
    setChmod
    createUploadDownloadPaths

    local intro="Uploading the directory '$WHAT' to '$WHERE'."
    local command="$RSYNC_CMD '$WHAT' '$WHERE'"
    local message="to upload data."
    executeCommand "$intro" "$command" "$message"
}



#
# Pull/download from the server
#
function dbwebb-download()
{
    #pullFromServer "$DBW_COURSE_DIR" "$DBW_REMOTE_DESTINATION" "$2"
    
    WHAT="$DBW_COURSE_DIR"
    WHERE="$DBW_REMOTE_DESTINATION"
    ITEM="$1"
    SUBDIR=""

    checkIfValidCourseRepoOrExit
    createUploadDownloadPaths

    local intro="Downloading the directory '$WHERE' to '$WHAT'.\nExisting local files that are newer will not be overwritten."
    local command="$RSYNC_DOWNLOAD_CMD '$WHERE' '$WHAT'"
    local message="to download data."
    executeCommand "$intro" "$command" "$message" "really?"
}



# --------------- DBWEBB FUNCTIONS PHASE END ---------------
# --------------- DBWEBB BOOTSTRAP PHASE START ---------------

#
# Specify the utilities used
#
ECHO="printf"
GIT="git"
RSYNC="rsync"
SSH="ssh"
SED="sed"
WGET="wget"
CURL="curl"
BASH="bash"
FIND="find"


# Revise these
UPLOAD="$RSYNC -av --delete --exclude literature --exclude .git -e \"ssh $DBW_SSH_KEY_OPTION\" \"$SOURCE\" \"$DESTINATION\""
UPLOAD_MINIMAL="$RSYNC -av --delete --exclude me --exclude tutorial --exclude example --exclude literature --exclude .git -e \"ssh $DBW_SSH_KEY_OPTION\" \"$SOURCE\" \"$DESTINATION\""


# Settins
MSG_OK="\033[0;30;42mOK\033[0m"
MSG_WARNING="\033[43mWARNING\033[0m"
MSG_FAILED="\033[0;37;41mFAILED\033[0m"


# For asserts
ASSERTS=0
FAULTS=0
TMPFILE="/tmp/dbwebb-error-{$USER}-$$"



#
# Find my environment, before any work can be done
#


# What was the command issued?
DBW_EXECUTABLE="$( basename "$0" )"

# Where is the executable
DBW_EXECUTABLE_DIR="$( dirname "$0" )"

# Where is the installation directory
#DBW_CLIDIR="dbwebb-cli"
#DBW_VERSION_FILE_NAME=".dbwebb.version"

#if [ -f "$DBW_EXECUTABLE_DIR/$DBW_VERSION_FILE_NAME" ]; then
#    DBW_INSTALL_DIR="$DBW_EXECUTABLE_DIR"
#elif [ -d "$DBWEBB_HOME" -a -d "$DBWEBB_HOME/$DBW_CLIDIR" ]; then
#    DBW_INSTALL_DIR="$DBWEBB_HOME/$DBW_CLIDIR"
#elif [ -d "$DBWEBB_CLI_HOME" ]; then
#    DBW_INSTALL_DIR="$DBWEBB_CLI_HOME"
#elif [ -d "$HOME/$DBW_BASEDIR/$DBW_CLIDIR" ]; then
#    DBW_INSTALL_DIR="$HOME/$DBW_BASEDIR/$DBW_CLIDIR"
#else 
#    $ECHO "$MSG_FAILED Could not determine the installation directory. I tried tried the environment variables \$DBWEBB_HOME and \$DBWEBB_CLI_HOME and looked in \$HOME/$DBW_BASEDIR/$DBW_CLIDIR.\n"
#    exit 1
#fi



# Get the current version installed as $DBW_VERSION
#DBW_VERSION_FILE="$DBW_INSTALL_DIR/$DBW_VERSION_FILE_NAME"
#if [ ! -f "$DBW_VERSION_FILE" ]; then
#    $ECHO "$MSG_FAILED Missing file $DBW_VERSION_FILE_NAME. The installation directory does not contain a valid installation.\n"
#    exit 1
#fi
#source "$DBW_VERSION_FILE"



# What is the current directory
DBW_CURRENT_DIR="$( pwd )"



# What is the directory of the current course repo, find recursivly up the tree
DBW_COURSE_FILE_NAME=".dbwebb.course"

dir="$DBW_CURRENT_DIR/."
while [ "$dir" != "/" ]; do 
    dir=$( dirname "$dir" )
    found="$( find "$dir" -maxdepth 1 -name $DBW_COURSE_FILE_NAME )"
    if [ "$found" ]; then 
        DBW_COURSE_DIR="$( dirname $found )"
        break
    fi
done



# Where is the directory for the course repos, if any
DBW_BASEDIR="dbwebb-kurser"
if [ -d "$DBWEBB_HOME" ]; then
    DBW_HOME="$DBW_BASEDIR"
elif [ -d "$HOME/$DBW_BASEDIR" ]; then
    DBW_HOME="$HOME/$DBW_BASEDIR"
fi



# Get the name of the course as $DBW_COURSE
DBW_COURSE_FILE="$DBW_COURSE_DIR/$DBW_COURSE_FILE_NAME"
DBW_COURSE_REPO_VALID=""
if [ -f "$DBW_COURSE_FILE" ]; then
    DBW_COURSE_REPO_VALID="yes"
    source "$DBW_COURSE_FILE"
fi



# Where is the .dbwebb.config-file
DBW_CONFIG_DEFAULT_FILE="$DBW_INSTALL_DIR/dbwebb2-config-sample"
DBW_CONFIG_FILE_NAME=".dbwebb.config"
DBW_CONFIG_FILE="$HOME/$DBW_CONFIG_FILE_NAME"
if [ ! -f "$DBW_CONFIG_FILE" ]; then

    # If the command is to init-repo, then execute that and create a config-file
    if [ "$1" = "init-repo" ]; then
        createConfig
        exit 0
    fi
else
    source "$DBW_CONFIG_FILE"
fi

# Name the remote server
DBW_HOST="ssh.student.bth.se"

# Check OS
DBW_OS="$( uname -a )"

# Create the ssh-command with details from the config-file
SSH_CMD="$SSH ${DBW_USER}@${DBW_HOST} $DBW_SSH_KEY_OPTION"

# Create the basis for the upload command
RSYNC_CMD="$RSYNC -av --delete --exclude .git --exclude .gitignore -e \"ssh $DBW_SSH_KEY_OPTION\""
RSYNC_DOWNLOAD_CMD="$RSYNC -avu -e \"ssh $DBW_SSH_KEY_OPTION\""

DBW_REMOTE_DESTINATION="${DBW_USER}@${DBW_HOST}:$DBW_BASEDIR/$DBW_COURSE"



# --------------- DBWEBB BOOTSTRAP PHASE END ---------------
# --------------- DBWEBB MAIN START HERE ---------------

#
# TODO Check how config-file is initiated
# Check if config file is up to date
#
updateConfigIfNeeded "update"



#
# TODO CLEAN UP THESE
# Get options
#
SKIP_READLINE="no"
IGNORE_FAULTS="-i"
VERY_VERBOSE="no"



#
# Process options
#
while (( $# ))
do
    case "$1" in
        
        --inspect | -i)
            printf %s "${inspectUsage[@]}"
            exit 0
        ;;

        --verbose | -v)
            VERY_VERBOSE="yes"
        ;;

        --yes | -y)
            SKIP_READLINE="yes"
        ;;

        --help | -h)
            printf %s "${usage[@]}"
            exit 0
        ;;
        
        --version)
            printf %s "${version[@]}"
            exit 0
        ;;
                
        clone)
            if [ -z "$2" ]; then
                $ECHO "\n$MSG_FAILED missing argument for repo name."
                $ECHO "\n"
                dbwebb2PrintShortUsage
                exit 1
            fi
            reposClone "$2"
            exit 0
        ;;

        selfupdate|self-update)
            selfUpdate
            exit 0
        ;;

#    init)
#        initServer
#        createDefaultFiles
#        #uploadToServer
#        ;;

        create)
            LAB="$2"
            if [ -z "$LAB" ]
            then
                echo "Missing name for lab, perhaps use lab1, lab2 or lab3?"
                exit 1
            fi
            createLab "$LAB"
            exit 0
        ;;

        validate)
            setChmod
            validateUploadedResults "$DBW_COURSE_DIR" "$DBW_REMOTE_DESTINATION" "$2"
            exit 0
        ;;

        publish)
            setChmod
            publishResults "$DBW_COURSE_DIR" "$DBW_REMOTE_DESTINATION" "$2"
            exit 0
        ;;

        inspect)
            WHICH=$2
            WHO=$3
            inspectResults ${WHICH:=all} ${WHO:=$USER}
            exit 0
        ;;

        update        \
        | check       \
        | config      \
        | ls          \
        | repo        \
        | sshkey      \
        | login       \
        | upload      \
        | download    \
        | init-server \
        | init-me)
            command=$1
            shift
            dbwebb-$command $*
            exit 0
        ;;
        
        *)
            printf "$MSG_FAILED Option/command not recognized.\n\n"
            printf %s "${badUsage[@]}"
            exit 1
        ;;
        
    esac
done

printf %s "${badUsage[@]}"
exit 1
